project:
  type: book
  output-dir: docs

book:
  title: "Reproducibly Analysing Visual-World Eyetracking Data"
  author: "Dale Barr"
  date: "10/26/2022"
  repo-url: https://github.com/dalejbarr/vw-analysis/
  sharing: [twitter, facebook]
  page-footer: "Copyright 2022, Dale J. Barr. Content licensed under Creative Commons CC-BY-SA."
  chapters:
    - index.qmd
    - part: "Pre-processing"
      chapters:
      - preprocessing_1.qmd
      - preprocessing_2.qmd
    - part: "Visualization and Analysis"
      chapters:
      - plotting.qmd
      - polynomial.qmd
      - clust-perm.qmd
  appendices:
    - references.qmd
    - data-structure.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



